module.exports = {
  "globDirectory": "bookfinal/",
  "globPatterns": [
    "**/*.svg",
    "**/*.png",
    "index.html",
    "index.css",
    "index.js",
    "offline.html",
    "offline.css",
    "common.css",
    "common.html",
    "assets-Error-Page/warning.gif",
    "manifest.json",
    "install.js",
    "errorpage.html",
    "errorpage.css",
  ],
  "swDest": "bookfinal/sw.js",
  "swSrc": "C:\\Users\\swati\\Desktop\\bookfinal\\service-worker.js",
};